//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcValidation.Models
{
    using System;
    using System.Collections.Generic;
    
    [System.ComponentModel.DataAnnotations.MetadataType(typeof(Curso_Validar))]
    public partial class Curso
    {
        public int codigo_c { get; set; }
        public string nombre_c { get; set; }
        public string correo_c { get; set; }
        public int credito_c { get; set; }
    }
}
