#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcLinqSql.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="bd_empresa")]
	public partial class DataEmpresaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Insertarea(area instance);
    partial void Updatearea(area instance);
    partial void Deletearea(area instance);
    #endregion
		
		public DataEmpresaDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["bd_empresaConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataEmpresaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataEmpresaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataEmpresaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataEmpresaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<area> area
		{
			get
			{
				return this.GetTable<area>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PR_ACTUALIZAR_AREA")]
		public int PR_ACTUALIZAR_AREA([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codigo2, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string descripcion2)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigo2, descripcion2);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PR_BUSCAR_AREA")]
		public ISingleResult<PR_BUSCAR_AREAResult> PR_BUSCAR_AREA([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codigo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigo);
			return ((ISingleResult<PR_BUSCAR_AREAResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PR_ELIMINAR_AREA")]
		public int PR_ELIMINAR_AREA([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codigo3)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigo3);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PR_INSERTAR_AREA")]
		public int PR_INSERTAR_AREA([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string descripcion_area)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), descripcion_area);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PR_LISTAR_AREA")]
		public ISingleResult<PR_LISTAR_AREAResult> PR_LISTAR_AREA()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<PR_LISTAR_AREAResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.area")]
	public partial class area : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _area_cod;
		
		private string _area_des;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onarea_codChanging(int value);
    partial void Onarea_codChanged();
    partial void Onarea_desChanging(string value);
    partial void Onarea_desChanged();
    #endregion
		
		public area()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_area_cod", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int area_cod
		{
			get
			{
				return this._area_cod;
			}
			set
			{
				if ((this._area_cod != value))
				{
					this.Onarea_codChanging(value);
					this.SendPropertyChanging();
					this._area_cod = value;
					this.SendPropertyChanged("area_cod");
					this.Onarea_codChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_area_des", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string area_des
		{
			get
			{
				return this._area_des;
			}
			set
			{
				if ((this._area_des != value))
				{
					this.Onarea_desChanging(value);
					this.SendPropertyChanging();
					this._area_des = value;
					this.SendPropertyChanged("area_des");
					this.Onarea_desChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class PR_BUSCAR_AREAResult
	{
		
		private int _area_cod;
		
		private string _area_des;
		
		public PR_BUSCAR_AREAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_area_cod", DbType="Int NOT NULL")]
		public int area_cod
		{
			get
			{
				return this._area_cod;
			}
			set
			{
				if ((this._area_cod != value))
				{
					this._area_cod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_area_des", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string area_des
		{
			get
			{
				return this._area_des;
			}
			set
			{
				if ((this._area_des != value))
				{
					this._area_des = value;
				}
			}
		}
	}
	
	public partial class PR_LISTAR_AREAResult
	{
		
		private int _area_cod;
		
		private string _area_des;
		
		public PR_LISTAR_AREAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_area_cod", DbType="Int NOT NULL")]
		public int area_cod
		{
			get
			{
				return this._area_cod;
			}
			set
			{
				if ((this._area_cod != value))
				{
					this._area_cod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_area_des", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string area_des
		{
			get
			{
				return this._area_des;
			}
			set
			{
				if ((this._area_des != value))
				{
					this._area_des = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
